### ISSUE TITLE
Doesn't work actually

### ISSUE THREAD

**Issue by ssommelet21** [zalo/ascii-chess#1]
Uncaught ReferenceError: SharedArrayBuffer is not defined
    at stockfish.js:33:131
    at index.js:17:1

**Comment by zalo** [comment]
Looks like there is a recent behavior where SharedArrayBuffers are outlawed unless you have the right HTTP Headers

Added a ServiceWorker hack to serve the correct headers with Github Pages:
https://github.com/gzuidhof/coi-serviceworker

Clear the browser cache and try loading the page again.

**Comment by ssommelet21** [comment]
Perfect !
